#oc create deployment my-dep --image=docker.io/nginx:latest --replicas=3 --port=8080 --dry-run=client -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-dep
  name: my-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-dep
    spec:
      containers:
      - image: docker.io/nginx:latest
        name: nginx
        ports:
        - containerPort: 8080
        resources: {}
status: {}
